### ISSUE TITLE
[1.20.1] Crash when opening mods menu for certain mods

### ISSUE THREAD

**Issue by katubug** [Carbon-Config-Project/CarbonConfig#12]
Hi Speiger and co! Hope you're well. I saw in your closed issues that you've been chasing this one for a minute, so I'm sorry to open a new ticket for it.

I also reported it to Night Config Fixes here: https://github.com/Fuzss/nightconfigfixes/issues/9
Because they're mentioned in the crash report. However, as I mentioned over there, it also occurs without Night Config Fixes installed.

Versions: 
MC: 1.20.1
Forge: 47.2.17
Carbon Config: 1.1.3

Here's the crash report: https://pastebin.com/Sy29g8W5

It doesn't happen when opening every mod config; for example the config for Jade works just fine. But the config for the mod Tarot Cards does (that's the most recent one, the only one I remember specifically).

Anyway, thanks for your time!

**Comment by Speiger** [comment]
o/ @katubug,
long time no see. 
I am doing all right, hope you are doing well too.

You are very lucky, and caught me when i was investigating carbon config at this point already.
This should be fixable from my end, ill look into it.

**Comment by Speiger** [comment]
Fix is now out!
