### ISSUE TITLE
[1.20.1 Forge] Crash with Blueprint

### ISSUE THREAD

**Issue by Crankonator** [Carbon-Config-Project/CarbonConfig#31]
Game crashes when I try accessing Blueprints shared config 

![image](https://github.com/Carbon-Config-Project/CarbonConfig/assets/108573834/ae9d6e83-1fc1-4b86-a1c7-3bf79d817354)

[crash-2024-04-19_20.25.33-client.txt](https://github.com/Carbon-Config-Project/CarbonConfig/files/15044399/crash-2024-04-19_20.25.33-client.txt)

**Comment by Speiger** [comment]
ty, i will take a look at it once i have a bit of free time.
(Might take a week sorry)

**Comment by Speiger** [comment]
@Crankonator 
Fixed for 1.18.2-1.20.5
It was basically a custom config they use where they get key/value pairs which carbon config doesn't support for forge configs.
I may add support for it later down the line, but i have to figure out how to do it because there is no "format structure" to follow.
