### ISSUE TITLE
Get Min and Max from ConfigEntries

### ISSUE THREAD

**Issue by Xaikii** [Carbon-Config-Project/CarbonConfig#32]
`public static IntValue SHIELD_VALUE = server.addInt("Shield Value", 20, "How many Health Points the Shield should be by default").setMin(0).setMax(65520);`
I can do SHIELD_VALUE.getDefault(), but .getMin() or .getMax() is not possible.

**Comment by Speiger** [comment]
@Xaikii i know you have a point but i have a question.
if you are working with constants in setMin/setMax why do you need to read them if you have the constants already known already.
(And updating mutliple of them could be achieved by using static final field)

(Note it will be added, but this is technically the wrong repo to make the issue on)
