### ISSUE TITLE
Crash on Neoforge 1.20.4 with Extended AE

### ISSUE THREAD

**Issue by Saereth** [Carbon-Config-Project/CarbonConfig#33]
https://mclo.gs/64xbSdR

Crash when attempting to open in game config with the Extended AE Mod and Carbon Config.
MC 1.20.4 
CarbonConfig-Neoforge-1.20.4-1.2.5.jar

**Comment by Speiger** [comment]
@Saereth oh god. Yeah Looks like i need to rewrite the forge (neoforges impl is based on forges) implementation to support a lot more.
Yeah i will try to get a patch out ASAP.
Might take a few days at worst.

**Comment by Speiger** [comment]
Fixed in 1.20.4 + other bugs found now propagating the fix to other versions
