### ISSUE TITLE
Crash on 1.7.10 with chunkpregnerator

### ISSUE THREAD

**Issue by reuben-matus** [Carbon-Config-Project/CarbonConfig#34]
[21:01:01] [Client thread/ERROR] [FML]: Caught exception from carbonconfig
java.lang.NoSuchMethodError: 'void speiger.src.collections.objects.maps.impl.hash.Object2ObjectOpenHashMap$MapEntry.set(int)'

mod list:

UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCH	CodeChickenCore{1.2.1} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{2.5.22-GTNH-pre} [NotEnoughItems] (NotEnoughItems-2.5.22-GTNH-pre.jar) 
	UCH	redirectionor{1.7.10} [Redirectionor] (minecraft.jar) 
	UCH	smoothfontcore{1.7.10-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UCH	VillagerMetaFix{0.3} [VillagerMetaFix] (VillagerMetaFix-0.4.jar) 
	UCH	chunkapicore{0.5.1} [ChunkAPI Core] (minecraft.jar) 
	UCH	FoamFixCore{1.0.4} [FoamFixCore] (minecraft.jar) 
	UCH	NettyPatch_ASM{0.1-Beta} [NettyPatch_ASM] (minecraft.jar) 
	UCH	smoothfont{1.7.10-1.15.3} [Smooth Font] (SmoothFont-1.7.10-1.15.3.jar) 
	UCH	MysteriumLib{1.1} [Â§5MysteriumÂ§aLib ] (!MysteriumLib-1.1.jar) 
	UCH	unimixins{0.1.17} [UniMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	unimixins-compat{0.1.17} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	mixinextras{0.1.17} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCH	libVulpes{0.2.8.-37} [libVulpes] (LibVulpes-1.7.10-0.2.8-37-universal.jar) 
	UCH	advancedRocketry{1.2.5} [Advanced Rocketry] (AdvancedRocketry-1.7.10-1.2.5.jar) 
	UCH	aiimprovements{0.0.1.8} [AI Improvements] (AIImprovements-1.7.10-0.0.1b8.jar) 
	UCH	alreadydecoratingfix{1.0a} [Already Decorating Fix] (alreadydecoratingfix-1.0a.jar) 
	UCH	embeddium{1.0.0-alpha53} [Embeddium] (angelica-1.0.0-alpha53.jar) 
	UCH	archaicfix{0.7.2} [ArchaicFix] (archaicfix-0.7.2.jar) 
	UCH	gtnhlib{0.3.2} [GTNH Lib] (gtnhlib-0.3.2.jar) 
	UCH	hodgepodge{2.5.16-pre} [Hodgepodge] (hodgepodge-2.5.16-pre.jar) 
	UCH	angelica{1.0.0-alpha53} [Angelica] (angelica-1.0.0-alpha53.jar) 
	UCH	notfine{1.0.0-alpha53} [NotFine] (angelica-1.0.0-alpha53.jar) 
	UCH	mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (angelica-1.0.0-alpha53.jar) 
	UCH	animalsPlus{1.2} [Animals+] (Animals-Plus-Mod-1.7.2-1.7.10.jar) 
	UCH	backhand{1.7.10} [Backhand] (backhand-1.4.0.jar) 
	UCH	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCH	betterboat{1.1.0} [Better Boat] (BetterBoat-1.7.10-1.1.0.jar) 
	UCH	biggerpacketsplz{1.2} [Bigger Packets, please !] (biggerpacketsplz-upto1.7.10-1.2.jar) 
	UCH	bugtorch{1.2.13} [BugTorch] (bugtorch-1.2.13.jar) 
	UCH	butterflymania{1.3.2} [Butterfly Mania] (butterflymania-1.7.10-1.3.2.jar) 
	UCH	campfirebackport{1.7.10-1.10.1} [Campfire Backport] (campfirebackport-1.7.10-1.10.1.jar) 
	UCE	carbonconfig{1.1.3} [Carbon Config Library] (CarbonConfig-1.7.10-1.2.4.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCH	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.2 - MC 1.7.10.jar) 
	UCE	chunkpregenerator{4.4.8} [Chunk Pregenerator] (Chunk-Pregenerator-1.7.10-4.4.8.jar) 
	UCH	falsepatternlib{1.2.4} [FalsePatternLib] (falsepatternlib-mc1.7.10-1.2.4.jar) 
	UCH	chunkapi{0.5.1} [ChunkAPI] (chunkapi-mc1.7.10-0.5.1.jar) 
	UCH	ChunkPurge{2.1} [Chunk Purge] (ChunkPurge-1.7.10-2.1.jar) 
	UCH	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCH	coretweaks{UNKNOWN-} [CoreTweaks] (CoreTweaks-1.7.10-UNKNOWN-.jar) 
	UCH	customnpcs{1.9.2} [CustomNPC+] (CustomNPC-Plus-1.9.2.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCH	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCH	dmod{1.0.3.5} [D-Mod] (DMod-1.7.10-1.0.3.5.jar) 
	UCH	jinryuujrmcore{1.3.51} [JinRyuu's JRMCore] (JRMCore-v1.3.51.jar) 
	UCH	jinryuudragonblockc{1.4.85} [Dragon Block C] (DragonBlockC-v1.4.85.jar) 
	UCH	entityculling{@VER@} [EntityCulling] (entityculling-1.6.4-mc1.7.10.jar) 
	UCH	erde{1.0c} [Entity Render Extender] (EntityRenderDistanceExtender-1.0c.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCH	etfuturum{2.6.0} [Â§5Â§oEt Futurum Requiem] (Et_Futurum_Requiem-2.6.0.jar) 
	UCH	falsetweaks{unspecified} [FalseTweaks] (falsetweaks-mc1.7.10.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.4.jar) 
	UCH	NBTEdit{1.7.10} [In-game NBTEdit] (ForgeNBTEdit-universal-1.0.0.test.jar) 
	UCH	FpsReducer{mc1.7.10-1.10.3} [FPS Reducer] (FpsReducer-mc1.7.10-1.10.3.jar) 
	UCH	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCH	jinryuubetterrenderaddon{1.6.52} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.52.jar) 
	UCH	jinryuufamilyc{1.2.18} [JinRyuu's Family C] (JFamilyC-v1.2.18(1).jar) 
	UCH	jinryuuhdskinsextended{1.3.1} [JinRyuu's HD Skins Extended] (JinRyuu's-HDSkins-Mod-1.7.10-v1.3.1.jar) 
	UCH	journeymap{5.2.5} [JourneyMap] (journeymap-1.7.10-5.2.5-unlimited.jar) 
	UCH	jaff{1.4.2_for_1.7.10} [Just a Few Fish] (JustAFewFish-1.4.2_for_1.7.10.jar) 
	UCH	jinryuuyearsc{1.2.5} [JinRyuu's Years C] (JYearsC-v1.2.5(1).jar) 
	UCH	leafculling{1.1.0.dirty} [Leaf Culling] (LeafCulling-mc1.7.10-1.1.0.dirty.jar) 
	UCH	legacyfixes{1.8.1} [LegacyFixes] (legacyfixes-1.8.1.jar) 
	UCH	lumi{1.0.0} [Lumi] (lumi-mc1.7.10-1.0.0.jar) 
	UCH	lwjgl3ify{2.1.1} [lwjgl3ify] (lwjgl3ify-2.1.1.jar) 
	UCH	millenaire{6.0.1} [MillÃ©naire] (Millenaire-Mod-Universal-1.7.10.jar) 
	UCH	mobends{0.20.1} [Mo' Bends] (MoBends-0.20.1 for MC 1.7.10.jar) 
	UCH	MoCreatures{1.1} [Mo' Creatures Legacy] (MoCreatures-Legacy-Final-1.1.jar) 
	UCH	cfm{3.4.7} [ï¿½9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCH	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.7.10-1.3.1.jar) 
	UCH	neodymium{0.3.3-unofficial} [Neodymium Unofficial] (neodymium-mc1.7.10-0.3.3-unofficial.jar) 
	UCH	netherlicious{3.2.8} [Â§6Netherlicious] (netherlicious-3.2.8.jar) 
	UCH	NettyPatch{0.2} [NettyPatch] (NettyPatcher-0.2.jar) 
	UCH	noleafdecay{1.0} [Â§cNo Â§aLeaf Â§2Decay] (noleafdecay-1.0.jar) 
	UCH	notenoughpets{2.3.6} [Â§eNot Enough Pets] (NotEnoughPets-1.7.10-2.3.6.jar) 
	UCH	nova_craft{1.3.4} [Â§3NovaCraftÂ§5] (NovaCraft V1.3.4 (1.7.10).jar) 
	UCH	npcaw{1.1} [CustomNPC-Plus-AW-Addon] (npcaw-1.1.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCH	pathfindertweaks{1.7.10-1.0.13} [PathfinderTweaks] (PathfinderTweaks-1.7.10-1.0.13.jar) 
	UCH	plug{5.1} [The Plugin Mod] (PluginMod-5.1.jar) 
	UCH	translationmod{6.0.1} [Real-time translation mod] (Real-Time-Chat-Translation-Mod-1.7.10.jar) 
	UCH	spark{1.10.35} [spark] (spark-1.10.19-forge1710.jar) 
	UCH	squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
	UCH	tabfaces{modversion} [TabFaces] (tabfaces-0.0.17-mc1.7.10.jar) 
	UCH	teresetfix{1.0.1-noreq} [TileEntity Reset Fix] (TileEntityResetFix-1.0.1-noreq.jar) 
	UCH	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
	UCH	ZoocraftDiscoveries{1.0} [Zoocraft Discoveries] (Zoocraft Discoveries 1.7.10-1.1.0.jar)

**Comment by Speiger** [comment]
@reuben-matus currently a incompat with ArchaicFix because we use the same library but both custom versions.
ArchaicFix dev already told me that they will change their library usage so it will be compatible with carbon config soon.

**Comment by reuben-matus** [comment]
Oh okay thanks
