### ISSUE TITLE
Crashing with Sodium on 1.21 neoforge

### ISSUE THREAD

**Issue by Saereth** [Carbon-Config-Project/CarbonConfig#38]
Minimal mod list, 
Neoforge 21.1.22
sodium-neoforge-0.6.0-beta.1+mc1.21.jar
CarbonConfig-Neoforge-1.21-1.2.9.1.jar

This is enough to cause the crash. Remove carbon config stops the crash and this is also true for our 300+ modpack, it crashes with sodium but removing carbon config or sodium will resolve the crash. 

Not sure who's side this is on so if I need to open an issue with sodium let me know, thanks!

Crash log:
https://mclo.gs/q4gZ7RN

**Comment by Speiger** [comment]
Fixed and pushed to CF
