### ISSUE TITLE
imports - ...screens.Screen...

### ISSUE THREAD

**Issue by ghost** [Carbon-Config-Project/CarbonConfig#39]
nmd

**Comment by RelivoF** [comment]
its the 1.20-fabric branch

**Comment by Speiger** [comment]
@RelivoF what the fuck was the about?

**Comment by ghost** [comment]
> @RelivoF what the fuck was the about?

I am a dumbass and did not realise they used a different mapping 🙃

**Comment by Speiger** [comment]
@RelivoF yeah i am using mojang maps because i am doing forge/neoforge/fabric support.
I have to have consistent code.
